spring.application.name=spring-blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blog
spring.datasource.username=blog
spring.datasource.password=blog

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
