spring.application.name=spring-blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blog
spring.datasource.username=blog
spring.datasource.password=blog

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
logging.level.org.flywaydb=DEBUG